In [2]:
np.random.rand(2,3)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
np.random.rand(2,3)

array([[0.95638036, 0.61357961, 0.05671147],
       [0.02465187, 0.91251286, 0.82304465]])

In [7]:
np.random.randint(1,5)

3

In [9]:
np.random.randint(1,5,size=(2,3))

array([[3, 2, 2],
       [1, 4, 1]], dtype=int32)

In [13]:
# give all the values randomly in the range which is given by user (start,end,no. of elements)
np.linspace(1,2,5) 

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
np.full((3,3,2),7)

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])

In [15]:
np.full((3,2),7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [16]:
arr=np.array([[2,3,4],[5,6,7]])

In [17]:
print(arr)

[[2 3 4]
 [5 6 7]]


In [22]:
arr[0].sum()

np.int64(9)

In [23]:
arr.sum(axis=0)

array([ 7,  9, 11])

In [24]:
arr.sum(axis=1)

array([ 9, 18])

In [35]:
arr1=np.full((3,3,2),5)

In [36]:
arr1

array([[[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])

In [37]:
arr1.sum()

np.int64(90)

In [38]:
arr1.sum(axis=0)

array([[15, 15],
       [15, 15],
       [15, 15]])

In [39]:
arr1.sum(axis=1)

array([[15, 15],
       [15, 15],
       [15, 15]])

In [46]:
arr3D=np.array([
    [
        [2,3,4],
        [5,6,4]
    ],
    [
        [3,4,5],
        [7,8,9]
    ]
])

In [47]:
arr3D

array([[[2, 3, 4],
        [5, 6, 4]],

       [[3, 4, 5],
        [7, 8, 9]]])

In [51]:
# axis 0 2+3 3+4 4+5 ----column wise on z axis
arr3D.sum(axis=0)

array([[ 5,  7,  9],
       [12, 14, 13]])

In [49]:
# 2+5 3+6 4+4  ---column wise on y axis
arr3D.sum(axis=1)

array([[ 7,  9,  8],
       [10, 12, 14]])

In [50]:
# 2+3+$  5+6 +4  -----row wise on x axis
arr3D.sum(axis=2)

array([[ 9, 15],
       [12, 24]])

In [58]:
np.average(arr3D)

np.float64(5.0)

In [59]:
np.max(arr3D)

np.int64(9)

In [60]:
np.min(arr3D)

np.int64(2)

In [62]:
np.min(arr3D,axis=0 )

array([[2, 3, 4],
       [5, 6, 4]])

In [64]:
# fancy indexing
arr2=np.array([2,3,4,5,6])
arr2[[1,3]]

array([3, 5])

In [67]:
# boolean masking
arr2[arr2 % 2==0] 

array([2, 4, 6])